name: Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Remove .md from links to match GH wiki format
      - name: Find and Replace links to .md files
        uses: shitiomatic/str-replace@master
        with:
          find: ".md"
          replace: ""
          includes: "docs/"

      # Upload documentation to the GH wiki
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "docs"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
